services:
  web_app:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tabloid_proteome_modpa_web_app
    restart: always
    ports:
      - 5600:5600