services:
  test_db: # web_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tabloid_proteome_modpa
    restart: always
    ports:
      - 5600:5600
